// frontend-next/src/app/auth/signup/page.tsx
"use client";

import { useRouter } from "next/navigation";
import React from "react";

const page = () => {
  const router = useRouter();
  const handleSubmit = (e: any) => {
    e.preventDefault();
  };
  return (
    <main className="md:min-w-[400px]">
      <header className="flex flex-col items-center justify-center"></header>
      <div className=" ">
        <form onSubmit={handleSubmit} className="flex flex-col gap-3">
          <label htmlFor="name" className="border-1 border">
            Name
          </label>
          <input name="username"></input>
          <label htmlFor="email">Email</label>
          <input name="email"></input>
          <label htmlFor="password">Password</label>
          <input name="password"></input>
          <button type="submit" className="bg-[#94a3b8]">
            Submit
          </button>
          <button
            className="bg-[#94a3b8]"
            onClick={() => router.push("/auth/signup")}
          >
            Sign up
          </button>
        </form>
      </div>
    </main>
  );
};

export default page;

// frontend/src/routes/user/sign-up/+page.svelte
<script lang="ts">
  import { enhance } from "$app/forms";
</script>

<div><h1>Sign up</h1></div>
<form class="flex flex-col gap-4" method="POST" use:enhance>
  <label class="input input-bordered flex items-center gap-2">
    Email
    <input type="text" name="email" class="grow" placeholder="daisy@site.com" />
  </label>
  <label class="input input-bordered flex items-center gap-2">
    Password
    <input type="text" name="password" class="grow" placeholder="Daisy" />
  </label>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
